{{- with .Values.global.clusterIssuers.acme }}
{{- if and .email .server .hmacKeyId .hmacKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: sectigo-hmac-key
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  secret: {{ .hmacKeySecret | b64enc }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sectigo
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1000"
spec:
  acme:
    email: {{ .email }}
    server: {{ .server }}
    externalAccountBinding:
      keyID: {{ .hmacKeyId }}
      keySecretRef:
        name: sectigo-hmac-key
        key: secret
    privateKeySecretRef:
      name: sectigo-cluster-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
{{- end }}
