global:
  # clusterIssuers (map): ClusterIssuers values.
  ##
  clusterIssuers:
    # acme (map): ACME ClusterIssuer configuration.
    ##
    acme:
      # email (string): Email to receive notifications from cert-manager.
      # Set by Terraform.
      email: ""
      # server (string): ACME server URL.
      # Set by Terraform.
      server: ""
      # hmacKeyId (string): ACME HMAC account key ID.
      # Set by Terraform.
      hmacKeyId: ""
      # hmacKeySecret (string): ACME HMAC account key secret value.
      # Set by Terraform.
      hmacKeySecret: ""

# cert-manager (map): cert-manager chart values.
##
cert-manager:
  # installCRDs (bool): Whether to install cert-manager CRDs.
  installCRDs: true

  # startupapicheck (map): Startup API check configuration.
  ##
  startupapicheck:
    # timeout (string): Startup API check timeout time.
    timeout: 5m
