apiVersion: v2
name: ingress-nginx
description: Ingress NGINX Controller
type: application
version: 0.1.0
dependencies:
- name: ingress-nginx
  version: 4.8.3
  repository: https://kubernetes.github.io/ingress-nginx
