# ingress-nginx (map): ingress-nginx chart values.
##
ingress-nginx:
  # controller (map): Controller values.
  ##
  controller:
    # kind (string): Type of object for controller deployment.
    kind: Deployment

    # admissionWebhooks (map): Admission webhooks configuration.
    ##
    admissionWebhooks:
      # enabled (bool): Whether to enable admission webhooks.
      enabled: false

    # service (map): Service configuration.
    ##
    service:
      # enabled (bool): Whether to enable Service.
      enabled: true
      # type (string): Service type.
      type: LoadBalancer
      # enableHttp (bool): Whether to enable HTTP endpoint.
      enableHttp: false
      # enableHttps (bool): Whether to enable HTTPS endpoint.
      enableHttps: true

      # nodePorts (map(string, number)): Service node port mapping configuration.
      ##
      nodePorts:
        # HTTPS port number.
        https: 30443

      # externalIPs (list(string)): List of Service external IP addresses.
      ##
      externalIPs:
      # External load balancer virtual IP address.
      # Set by Terraform.
      - ""

    # config (map): Controller configuration.
    ##
    config:
      # hsts (bool): Whether to enable HSTS policy.
      # Force clients to establish HTTPS connection.
      hsts: true
      # hsts-include-subdomains (bool): Whether to enable HSTS for subdomains.
      hsts-include-subdomains: true

    # ingressClassResource (map): IngressClass configuration.
    ##
    ingressClassResource:
      # default (bool): Whether to make IngressCrass default.
      default: true
