{{- if index .Values "kube-prometheus-stack" "alertmanager" "ingress" "annotations" "nginx.ingress.kubernetes.io/auth-type" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "kube-prometheus-stack" "alertmanager" "ingress" "annotations" "nginx.ingress.kubernetes.io/auth-secret" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd .Values.alertmanager.basicAuth.user .Values.alertmanager.basicAuth.password | b64enc }}
{{- end }}
