---
- name: Disable swap
  ansible.builtin.shell: swapoff -a
  changed_when: ansible_swaptotal_mb > 0

- name: Disable swap in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
