# coredns (map): CoreDNS chart values.
##
coredns:
  # fullnameOverride (string): Override for prefix of CoreDNS-related objects.
  fullnameOverride: coredns

  # image (map): CoreDNS image configuration.
  ##
  image:
    # repository (string): URL of image repository (without `https://`).
    # Set by Terraform.
    repository: ""

  # replicaCount (number): Amount of CoreDNS Pods.
  replicaCount: 2

  # isClusterService (bool): Whether to deploy CoreDNS as cluster service discovery.
  isClusterService: true

  # service (map): Service configuration.
  ##
  service:
    # clusterIP (string): Service IP address in cluster.
    clusterIP: ""
