{{- if .Values.longhorn.defaultSettings.backupTargetCredentialSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.longhorn.defaultSettings.backupTargetCredentialSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ENDPOINTS: {{ .Values.s3Backup.endpoint | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3Backup.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3Backup.secretAccessKey | b64enc }}
{{- end }}
