{{- if index .Values.longhorn.ingress.annotations "nginx.ingress.kubernetes.io/auth-type" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values.longhorn.ingress.annotations "nginx.ingress.kubernetes.io/auth-secret" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd .Values.basicAuth.adminUser .Values.basicAuth.adminPassword | b64enc }}
{{- end }}
