{{- if index .Values.longhorn.ingress.annotations "nginx.ingress.kubernetes.io/auth-type" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values.longhorn.ingress.annotations "nginx.ingress.kubernetes.io/auth-secret" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{
    htpasswd
      .Values.longhorn.longhornUI.auth.adminUser
      .Values.longhorn.longhornUI.auth.adminPassword
    | b64enc
  }}
{{- end }}
