---
- name: Install nginx exporter package
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Copy nginx exporter default configuration
  ansible.builtin.template:
    src: prometheus-nginx-exporter.j2
    dest: /etc/default/prometheus-nginx-exporter

- name: Enable nginx exporter service
  ansible.builtin.systemd_service:
    name: prometheus-nginx-exporter
    state: restarted
    enabled: true
