---
- name: Install required apt packages
  ansible.builtin.apt:
    deb: https://github.com/mehdy/keepalived-exporter/releases/download/v1.3.2/keepalived-exporter-1.3.2.linux-amd64.deb

- name: Create symlink for keepalived exporter binary with new name
  ansible.builtin.file:
    src: /usr/bin/keepalived-exporter
    dest: /usr/bin/prometheus-keepalived-exporter
    state: link

- name: Copy keepalived exporter unit file
  ansible.builtin.copy:
    src: prometheus-keepalived-exporter.service
    dest: /etc/systemd/system/prometheus-keepalived-exporter.service

- name: Enable keepalived exporter service
  ansible.builtin.systemd_service:
    name: prometheus-keepalived-exporter
    state: started
    enabled: true
    daemon_reload: true
