---
- name: Install apt packages
  ansible.builtin.apt:
    name: keepalived=1:2.2.*

- name: Generate random password
  run_once: true
  ansible.builtin.set_fact:
    keepalived_password: "{{ lookup('password', '/dev/null', length=8) }}"

- name: Copy configuration file
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf.tmp
    mode: 0640

- name: Test configuration
  ansible.builtin.shell:
    cmd: keepalived -t -f /etc/keepalived/keepalived.conf.tmp
  ignore_errors: true
  register: test_config

- name: Apply configuration if test succeeded
  ansible.builtin.copy:
    src: /etc/keepalived/keepalived.conf.tmp
    dest: /etc/keepalived/keepalived.conf
    remote_src: true
  when: not test_config.failed

- name: Remove temporary configuration file
  ansible.builtin.file:
    path: /etc/keepalived/keepalived.conf.tmp
    state: absent

- name: Enable keepalived service
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
    enabled: true
