- job_name: nginx
  static_configs:
  - targets:
    {{- .Values.exporters.nginx.endpoints | toYaml | nindent 4 }}
- job_name: keepalived
  static_configs:
  - targets:
    {{- .Values.exporters.keepalived.endpoints | toYaml | nindent 4 }}
