apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "kube-prometheus-stack" "prometheus" "prometheusSpec" "secrets" 0 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.etcd.caCrt | b64enc }}
  client.crt: {{ .Values.etcd.clientCert | b64enc }}
  client.key: {{ .Values.etcd.clientKey | b64enc }}
