{{ if index .Values "kube-prometheus-stack" "prometheus" "prometheusSpec" "additionalScrapeConfigsSecret" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "kube-prometheus-stack" "prometheus" "prometheusSpec" "additionalScrapeConfigsSecret" "name" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ index .Values "kube-prometheus-stack" "prometheus" "prometheusSpec" "additionalScrapeConfigsSecret" "key" }}: {{ tpl (.Files.Get "files/scrape-configs.yaml") . | b64enc }}
{{- end }}
