
# auth (map): Authentication configuration.
##
basicAuth:
  # adminUser (string): Basic authentication username
  adminUser: ""
  # adminPassword (string): Basic authentication password
  adminPassword: ""

# s3 (map): S3 backup configuration.
##
s3Backup:
  # endpoint (string): S3 endpoint
  endpoint: ""
  # accessKeyId (string): S3 access key ID
  accessKeyId: ""
  # secretAccessKey (string): S3 secret access key.
  secretAccessKey: ""

# longhorn (map): Longhorn chart values.
##
longhorn:
  # defaultSettings (map): Longhorn configuration settings.
  ##
  defaultSettings:
    # Default data directory path mapping on Kubernetes hosts.
    defaultDataPath: /data
    # Whether to enable Longhorn chart uninstallation.
    deletingConfirmationFlag: true
    # Percentage of reserved disk space.
    storageReservedPercentageForDefaultDisk: 10
    # Backup target location.
    backupTarget: ""
    # Secret containing credentials to access backup target.
    backupTargetCredentialSecret: backup-target
    # Policy of StatefulSet and Deployment Pods deletion on failed nodes.
    # Needed for automatic reattachment of PVCs during Pods reschedule.
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    # Amount of PVC replicas created through Longhorn UI.
    defaultReplicaCount: 2

  # privateRegistry (map): Private registry configuration.
  ##
  privateRegistry:
    # registryUrl (string): URL of image registry (without `https://`).
    # Set By Terraform.
    registryUrl: ""

  # ingress (map): Grafana Ingress configuration.
  ##
  ingress:
    # enabled (bool): Whether to create Ingress object.
    enabled: true
    # host (string): Ingress hostname.
    host: ""
    # path (string): Ingress path.
    path: /
    # tls (bool): Whether to enable TLS for Ingress host.
    tls: true
    # tlsSecret (string): Name of Secret containing hostname TLS certificates.
    tlsSecret: ""

    annotations:
      # Annotations for cert-manager. More: https://github.com/cert-manager/cert-manager.
      ##
      # Cluster issuer name to use for TLS certificate issuing.
      cert-manager.io/cluster-issuer: sectigo

      # Annotations for ingress controller.
      ##
      # Maximum allowed size of client request body.
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m
      # Type of authentication used when accessing hostnames configures in ingress.
      nginx.ingress.kubernetes.io/auth-type: basic
      # Name of secret object which contains authentication credentials.
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      # Message to include in HTTP response header.
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required "

      # Annotations for Forecastle. More: https://github.com/stakater/Forecastle.
      ##
      # Whether to display ingress in Forecastle.
      forecastle.stakater.com/expose: "true"
      # Name of group under which ingress is displayed in Forecastle.
      forecastle.stakater.com/group: management
      # Override for name under which ingress is displayed in Forecastle.
      forecastle.stakater.com/appName: Longhorn
      # URL of icon/image to display with ingress in Forecastle.
      forecastle.stakater.com/icon: https://longhorn.io/img/logos/longhorn-icon-color.png

  # persistence (map): Persistence configuration.
  ##
  persistence:
    # defaultClassReplicaCount (number): Amount of PVC replicas provided by Longhorn StorageClass.
    defaultClassReplicaCount: 2
